server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/johjanbaquerom/microservicios-practica
          search-paths: config-data
  application:
    name: config-service        